// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package common.protobuf;

public final class MsgBuilder {
  private MsgBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code common.protobuf.ChatType}
   */
  public enum ChatType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Text = 1;</code>
     */
    Text(1),
    /**
     * <code>Photo = 2;</code>
     */
    Photo(2),
    /**
     * <code>Audio = 3;</code>
     */
    Audio(3),
    ;

    /**
     * <code>Text = 1;</code>
     */
    public static final int Text_VALUE = 1;
    /**
     * <code>Photo = 2;</code>
     */
    public static final int Photo_VALUE = 2;
    /**
     * <code>Audio = 3;</code>
     */
    public static final int Audio_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChatType valueOf(int value) {
      return forNumber(value);
    }

    public static ChatType forNumber(int value) {
      switch (value) {
        case 1: return Text;
        case 2: return Photo;
        case 3: return Audio;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChatType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChatType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChatType>() {
            public ChatType findValueByNumber(int number) {
              return ChatType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return common.protobuf.MsgBuilder.getDescriptor().getEnumTypes().get(0);
    }

    private static final ChatType[] VALUES = values();

    public static ChatType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChatType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:common.protobuf.ChatType)
  }

  /**
   * <pre>
   *enum CmdType{
   *Greet = 1;
   *LoadID = 2;
   *LoadMsg = 3;
   *}
   * </pre>
   *
   * Protobuf enum {@code common.protobuf.AckState}
   */
  public enum AckState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ClientSend = 1;</code>
     */
    ClientSend(1),
    /**
     * <code>ServerReceive = 2;</code>
     */
    ServerReceive(2),
    /**
     * <code>ServerSend = 3;</code>
     */
    ServerSend(3),
    /**
     * <code>ClientReceive = 4;</code>
     */
    ClientReceive(4),
    /**
     * <code>ClientRead = 5;</code>
     */
    ClientRead(5),
    /**
     * <code>ServerRead = 6;</code>
     */
    ServerRead(6),
    /**
     * <code>Error = 7;</code>
     */
    Error(7),
    ;

    /**
     * <code>ClientSend = 1;</code>
     */
    public static final int ClientSend_VALUE = 1;
    /**
     * <code>ServerReceive = 2;</code>
     */
    public static final int ServerReceive_VALUE = 2;
    /**
     * <code>ServerSend = 3;</code>
     */
    public static final int ServerSend_VALUE = 3;
    /**
     * <code>ClientReceive = 4;</code>
     */
    public static final int ClientReceive_VALUE = 4;
    /**
     * <code>ClientRead = 5;</code>
     */
    public static final int ClientRead_VALUE = 5;
    /**
     * <code>ServerRead = 6;</code>
     */
    public static final int ServerRead_VALUE = 6;
    /**
     * <code>Error = 7;</code>
     */
    public static final int Error_VALUE = 7;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AckState valueOf(int value) {
      return forNumber(value);
    }

    public static AckState forNumber(int value) {
      switch (value) {
        case 1: return ClientSend;
        case 2: return ServerReceive;
        case 3: return ServerSend;
        case 4: return ClientReceive;
        case 5: return ClientRead;
        case 6: return ServerRead;
        case 7: return Error;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AckState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AckState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AckState>() {
            public AckState findValueByNumber(int number) {
              return AckState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return common.protobuf.MsgBuilder.getDescriptor().getEnumTypes().get(1);
    }

    private static final AckState[] VALUES = values();

    public static AckState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AckState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:common.protobuf.AckState)
  }

  /**
   * <pre>
   *全局共有的
   * </pre>
   *
   * Protobuf enum {@code common.protobuf.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Ping = 1;</code>
     */
    Ping(1),
    /**
     * <code>Pong = 2;</code>
     */
    Pong(2),
    /**
     * <code>Chat = 3;</code>
     */
    Chat(3),
    /**
     * <code>ChatAck = 4;</code>
     */
    ChatAck(4),
    /**
     * <code>CMD = 5;</code>
     */
    CMD(5),
    /**
     * <code>Broadcast = 6;</code>
     */
    Broadcast(6),
    /**
     * <code>GroupChat = 7;</code>
     */
    GroupChat(7),
    ;

    /**
     * <code>Ping = 1;</code>
     */
    public static final int Ping_VALUE = 1;
    /**
     * <code>Pong = 2;</code>
     */
    public static final int Pong_VALUE = 2;
    /**
     * <code>Chat = 3;</code>
     */
    public static final int Chat_VALUE = 3;
    /**
     * <code>ChatAck = 4;</code>
     */
    public static final int ChatAck_VALUE = 4;
    /**
     * <code>CMD = 5;</code>
     */
    public static final int CMD_VALUE = 5;
    /**
     * <code>Broadcast = 6;</code>
     */
    public static final int Broadcast_VALUE = 6;
    /**
     * <code>GroupChat = 7;</code>
     */
    public static final int GroupChat_VALUE = 7;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 1: return Ping;
        case 2: return Pong;
        case 3: return Chat;
        case 4: return ChatAck;
        case 5: return CMD;
        case 6: return Broadcast;
        case 7: return GroupChat;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return common.protobuf.MsgBuilder.getDescriptor().getEnumTypes().get(2);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:common.protobuf.MsgType)
  }

  public interface ProtoMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.protobuf.ProtoMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional int32 from_id = 2;</code>
     */
    boolean hasFromId();
    /**
     * <code>optional int32 from_id = 2;</code>
     */
    int getFromId();

    /**
     * <code>optional int32 dest_id = 3;</code>
     */
    boolean hasDestId();
    /**
     * <code>optional int32 dest_id = 3;</code>
     */
    int getDestId();

    /**
     * <code>optional int64 client_id = 4;</code>
     */
    boolean hasClientId();
    /**
     * <code>optional int64 client_id = 4;</code>
     */
    long getClientId();

    /**
     * <code>optional string dialog_id = 5;</code>
     */
    boolean hasDialogId();
    /**
     * <code>optional string dialog_id = 5;</code>
     */
    java.lang.String getDialogId();
    /**
     * <code>optional string dialog_id = 5;</code>
     */
    com.google.protobuf.ByteString
        getDialogIdBytes();

    /**
     * <code>required .common.protobuf.MsgType msg_type = 6;</code>
     */
    boolean hasMsgType();
    /**
     * <code>required .common.protobuf.MsgType msg_type = 6;</code>
     */
    common.protobuf.MsgBuilder.MsgType getMsgType();

    /**
     * <code>optional string body = 7;</code>
     */
    boolean hasBody();
    /**
     * <code>optional string body = 7;</code>
     */
    java.lang.String getBody();
    /**
     * <code>optional string body = 7;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>optional .common.protobuf.AckState state = 8;</code>
     */
    boolean hasState();
    /**
     * <code>optional .common.protobuf.AckState state = 8;</code>
     */
    common.protobuf.MsgBuilder.AckState getState();

    /**
     * <code>optional uint64 time = 9;</code>
     */
    boolean hasTime();
    /**
     * <code>optional uint64 time = 9;</code>
     */
    long getTime();

    /**
     * <code>optional string cmd = 10;</code>
     */
    boolean hasCmd();
    /**
     * <code>optional string cmd = 10;</code>
     */
    java.lang.String getCmd();
    /**
     * <code>optional string cmd = 10;</code>
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>required .common.protobuf.ChatType chat_type = 11;</code>
     */
    boolean hasChatType();
    /**
     * <code>required .common.protobuf.ChatType chat_type = 11;</code>
     */
    common.protobuf.MsgBuilder.ChatType getChatType();
  }
  /**
   * Protobuf type {@code common.protobuf.ProtoMsg}
   */
  public  static final class ProtoMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.protobuf.ProtoMsg)
      ProtoMsgOrBuilder {
    // Use ProtoMsg.newBuilder() to construct.
    private ProtoMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoMsg() {
      id_ = 0L;
      fromId_ = 0;
      destId_ = 0;
      clientId_ = 0L;
      dialogId_ = "";
      msgType_ = 1;
      body_ = "";
      state_ = 1;
      time_ = 0L;
      cmd_ = "";
      chatType_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fromId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              destId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              clientId_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              dialogId_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              common.protobuf.MsgBuilder.MsgType value = common.protobuf.MsgBuilder.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                msgType_ = rawValue;
              }
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              body_ = bs;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              common.protobuf.MsgBuilder.AckState value = common.protobuf.MsgBuilder.AckState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                state_ = rawValue;
              }
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              time_ = input.readUInt64();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              cmd_ = bs;
              break;
            }
            case 88: {
              int rawValue = input.readEnum();
              common.protobuf.MsgBuilder.ChatType value = common.protobuf.MsgBuilder.ChatType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(11, rawValue);
              } else {
                bitField0_ |= 0x00000400;
                chatType_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common.protobuf.MsgBuilder.internal_static_common_protobuf_ProtoMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common.protobuf.MsgBuilder.internal_static_common_protobuf_ProtoMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              common.protobuf.MsgBuilder.ProtoMsg.class, common.protobuf.MsgBuilder.ProtoMsg.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int FROM_ID_FIELD_NUMBER = 2;
    private int fromId_;
    /**
     * <code>optional int32 from_id = 2;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 from_id = 2;</code>
     */
    public int getFromId() {
      return fromId_;
    }

    public static final int DEST_ID_FIELD_NUMBER = 3;
    private int destId_;
    /**
     * <code>optional int32 dest_id = 3;</code>
     */
    public boolean hasDestId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 dest_id = 3;</code>
     */
    public int getDestId() {
      return destId_;
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 4;
    private long clientId_;
    /**
     * <code>optional int64 client_id = 4;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 client_id = 4;</code>
     */
    public long getClientId() {
      return clientId_;
    }

    public static final int DIALOG_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object dialogId_;
    /**
     * <code>optional string dialog_id = 5;</code>
     */
    public boolean hasDialogId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string dialog_id = 5;</code>
     */
    public java.lang.String getDialogId() {
      java.lang.Object ref = dialogId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dialogId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dialog_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDialogIdBytes() {
      java.lang.Object ref = dialogId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dialogId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 6;
    private int msgType_;
    /**
     * <code>required .common.protobuf.MsgType msg_type = 6;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .common.protobuf.MsgType msg_type = 6;</code>
     */
    public common.protobuf.MsgBuilder.MsgType getMsgType() {
      common.protobuf.MsgBuilder.MsgType result = common.protobuf.MsgBuilder.MsgType.valueOf(msgType_);
      return result == null ? common.protobuf.MsgBuilder.MsgType.Ping : result;
    }

    public static final int BODY_FIELD_NUMBER = 7;
    private volatile java.lang.Object body_;
    /**
     * <code>optional string body = 7;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string body = 7;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string body = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 8;
    private int state_;
    /**
     * <code>optional .common.protobuf.AckState state = 8;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .common.protobuf.AckState state = 8;</code>
     */
    public common.protobuf.MsgBuilder.AckState getState() {
      common.protobuf.MsgBuilder.AckState result = common.protobuf.MsgBuilder.AckState.valueOf(state_);
      return result == null ? common.protobuf.MsgBuilder.AckState.ClientSend : result;
    }

    public static final int TIME_FIELD_NUMBER = 9;
    private long time_;
    /**
     * <code>optional uint64 time = 9;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint64 time = 9;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int CMD_FIELD_NUMBER = 10;
    private volatile java.lang.Object cmd_;
    /**
     * <code>optional string cmd = 10;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string cmd = 10;</code>
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cmd = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHAT_TYPE_FIELD_NUMBER = 11;
    private int chatType_;
    /**
     * <code>required .common.protobuf.ChatType chat_type = 11;</code>
     */
    public boolean hasChatType() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required .common.protobuf.ChatType chat_type = 11;</code>
     */
    public common.protobuf.MsgBuilder.ChatType getChatType() {
      common.protobuf.MsgBuilder.ChatType result = common.protobuf.MsgBuilder.ChatType.valueOf(chatType_);
      return result == null ? common.protobuf.MsgBuilder.ChatType.Text : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChatType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, destId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, clientId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dialogId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, msgType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, body_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, state_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt64(9, time_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, cmd_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeEnum(11, chatType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, destId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, clientId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dialogId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, msgType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, body_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, state_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, time_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, cmd_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, chatType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof common.protobuf.MsgBuilder.ProtoMsg)) {
        return super.equals(obj);
      }
      common.protobuf.MsgBuilder.ProtoMsg other = (common.protobuf.MsgBuilder.ProtoMsg) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasFromId() == other.hasFromId());
      if (hasFromId()) {
        result = result && (getFromId()
            == other.getFromId());
      }
      result = result && (hasDestId() == other.hasDestId());
      if (hasDestId()) {
        result = result && (getDestId()
            == other.getDestId());
      }
      result = result && (hasClientId() == other.hasClientId());
      if (hasClientId()) {
        result = result && (getClientId()
            == other.getClientId());
      }
      result = result && (hasDialogId() == other.hasDialogId());
      if (hasDialogId()) {
        result = result && getDialogId()
            .equals(other.getDialogId());
      }
      result = result && (hasMsgType() == other.hasMsgType());
      if (hasMsgType()) {
        result = result && msgType_ == other.msgType_;
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && (hasState() == other.hasState());
      if (hasState()) {
        result = result && state_ == other.state_;
      }
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && (getTime()
            == other.getTime());
      }
      result = result && (hasCmd() == other.hasCmd());
      if (hasCmd()) {
        result = result && getCmd()
            .equals(other.getCmd());
      }
      result = result && (hasChatType() == other.hasChatType());
      if (hasChatType()) {
        result = result && chatType_ == other.chatType_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasFromId()) {
        hash = (37 * hash) + FROM_ID_FIELD_NUMBER;
        hash = (53 * hash) + getFromId();
      }
      if (hasDestId()) {
        hash = (37 * hash) + DEST_ID_FIELD_NUMBER;
        hash = (53 * hash) + getDestId();
      }
      if (hasClientId()) {
        hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getClientId());
      }
      if (hasDialogId()) {
        hash = (37 * hash) + DIALOG_ID_FIELD_NUMBER;
        hash = (53 * hash) + getDialogId().hashCode();
      }
      if (hasMsgType()) {
        hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + msgType_;
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + state_;
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
      }
      if (hasCmd()) {
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + getCmd().hashCode();
      }
      if (hasChatType()) {
        hash = (37 * hash) + CHAT_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + chatType_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static common.protobuf.MsgBuilder.ProtoMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common.protobuf.MsgBuilder.ProtoMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common.protobuf.MsgBuilder.ProtoMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common.protobuf.MsgBuilder.ProtoMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common.protobuf.MsgBuilder.ProtoMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static common.protobuf.MsgBuilder.ProtoMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static common.protobuf.MsgBuilder.ProtoMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static common.protobuf.MsgBuilder.ProtoMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static common.protobuf.MsgBuilder.ProtoMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static common.protobuf.MsgBuilder.ProtoMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(common.protobuf.MsgBuilder.ProtoMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.protobuf.ProtoMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.protobuf.ProtoMsg)
        common.protobuf.MsgBuilder.ProtoMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return common.protobuf.MsgBuilder.internal_static_common_protobuf_ProtoMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return common.protobuf.MsgBuilder.internal_static_common_protobuf_ProtoMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                common.protobuf.MsgBuilder.ProtoMsg.class, common.protobuf.MsgBuilder.ProtoMsg.Builder.class);
      }

      // Construct using common.protobuf.MsgBuilder.ProtoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        fromId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        destId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        clientId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        dialogId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        msgType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000020);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        state_ = 1;
        bitField0_ = (bitField0_ & ~0x00000080);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        cmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        chatType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common.protobuf.MsgBuilder.internal_static_common_protobuf_ProtoMsg_descriptor;
      }

      public common.protobuf.MsgBuilder.ProtoMsg getDefaultInstanceForType() {
        return common.protobuf.MsgBuilder.ProtoMsg.getDefaultInstance();
      }

      public common.protobuf.MsgBuilder.ProtoMsg build() {
        common.protobuf.MsgBuilder.ProtoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public common.protobuf.MsgBuilder.ProtoMsg buildPartial() {
        common.protobuf.MsgBuilder.ProtoMsg result = new common.protobuf.MsgBuilder.ProtoMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destId_ = destId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dialogId_ = dialogId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.chatType_ = chatType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common.protobuf.MsgBuilder.ProtoMsg) {
          return mergeFrom((common.protobuf.MsgBuilder.ProtoMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(common.protobuf.MsgBuilder.ProtoMsg other) {
        if (other == common.protobuf.MsgBuilder.ProtoMsg.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasFromId()) {
          setFromId(other.getFromId());
        }
        if (other.hasDestId()) {
          setDestId(other.getDestId());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasDialogId()) {
          bitField0_ |= 0x00000010;
          dialogId_ = other.dialogId_;
          onChanged();
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000040;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasCmd()) {
          bitField0_ |= 0x00000200;
          cmd_ = other.cmd_;
          onChanged();
        }
        if (other.hasChatType()) {
          setChatType(other.getChatType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasMsgType()) {
          return false;
        }
        if (!hasChatType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        common.protobuf.MsgBuilder.ProtoMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (common.protobuf.MsgBuilder.ProtoMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int fromId_ ;
      /**
       * <code>optional int32 from_id = 2;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 from_id = 2;</code>
       */
      public int getFromId() {
        return fromId_;
      }
      /**
       * <code>optional int32 from_id = 2;</code>
       */
      public Builder setFromId(int value) {
        bitField0_ |= 0x00000002;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 from_id = 2;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromId_ = 0;
        onChanged();
        return this;
      }

      private int destId_ ;
      /**
       * <code>optional int32 dest_id = 3;</code>
       */
      public boolean hasDestId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 dest_id = 3;</code>
       */
      public int getDestId() {
        return destId_;
      }
      /**
       * <code>optional int32 dest_id = 3;</code>
       */
      public Builder setDestId(int value) {
        bitField0_ |= 0x00000004;
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dest_id = 3;</code>
       */
      public Builder clearDestId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destId_ = 0;
        onChanged();
        return this;
      }

      private long clientId_ ;
      /**
       * <code>optional int64 client_id = 4;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 client_id = 4;</code>
       */
      public long getClientId() {
        return clientId_;
      }
      /**
       * <code>optional int64 client_id = 4;</code>
       */
      public Builder setClientId(long value) {
        bitField0_ |= 0x00000008;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 client_id = 4;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object dialogId_ = "";
      /**
       * <code>optional string dialog_id = 5;</code>
       */
      public boolean hasDialogId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string dialog_id = 5;</code>
       */
      public java.lang.String getDialogId() {
        java.lang.Object ref = dialogId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dialogId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dialog_id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDialogIdBytes() {
        java.lang.Object ref = dialogId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dialogId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dialog_id = 5;</code>
       */
      public Builder setDialogId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dialogId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dialog_id = 5;</code>
       */
      public Builder clearDialogId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dialogId_ = getDefaultInstance().getDialogId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dialog_id = 5;</code>
       */
      public Builder setDialogIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dialogId_ = value;
        onChanged();
        return this;
      }

      private int msgType_ = 1;
      /**
       * <code>required .common.protobuf.MsgType msg_type = 6;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .common.protobuf.MsgType msg_type = 6;</code>
       */
      public common.protobuf.MsgBuilder.MsgType getMsgType() {
        common.protobuf.MsgBuilder.MsgType result = common.protobuf.MsgBuilder.MsgType.valueOf(msgType_);
        return result == null ? common.protobuf.MsgBuilder.MsgType.Ping : result;
      }
      /**
       * <code>required .common.protobuf.MsgType msg_type = 6;</code>
       */
      public Builder setMsgType(common.protobuf.MsgBuilder.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .common.protobuf.MsgType msg_type = 6;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgType_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>optional string body = 7;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000040);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        body_ = value;
        onChanged();
        return this;
      }

      private int state_ = 1;
      /**
       * <code>optional .common.protobuf.AckState state = 8;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .common.protobuf.AckState state = 8;</code>
       */
      public common.protobuf.MsgBuilder.AckState getState() {
        common.protobuf.MsgBuilder.AckState result = common.protobuf.MsgBuilder.AckState.valueOf(state_);
        return result == null ? common.protobuf.MsgBuilder.AckState.ClientSend : result;
      }
      /**
       * <code>optional .common.protobuf.AckState state = 8;</code>
       */
      public Builder setState(common.protobuf.MsgBuilder.AckState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .common.protobuf.AckState state = 8;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000080);
        state_ = 1;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional uint64 time = 9;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint64 time = 9;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional uint64 time = 9;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000100;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 time = 9;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        time_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>optional string cmd = 10;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string cmd = 10;</code>
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cmd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cmd = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cmd = 10;</code>
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmd = 10;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000200);
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmd = 10;</code>
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        cmd_ = value;
        onChanged();
        return this;
      }

      private int chatType_ = 1;
      /**
       * <code>required .common.protobuf.ChatType chat_type = 11;</code>
       */
      public boolean hasChatType() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required .common.protobuf.ChatType chat_type = 11;</code>
       */
      public common.protobuf.MsgBuilder.ChatType getChatType() {
        common.protobuf.MsgBuilder.ChatType result = common.protobuf.MsgBuilder.ChatType.valueOf(chatType_);
        return result == null ? common.protobuf.MsgBuilder.ChatType.Text : result;
      }
      /**
       * <code>required .common.protobuf.ChatType chat_type = 11;</code>
       */
      public Builder setChatType(common.protobuf.MsgBuilder.ChatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000400;
        chatType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .common.protobuf.ChatType chat_type = 11;</code>
       */
      public Builder clearChatType() {
        bitField0_ = (bitField0_ & ~0x00000400);
        chatType_ = 1;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.protobuf.ProtoMsg)
    }

    // @@protoc_insertion_point(class_scope:common.protobuf.ProtoMsg)
    private static final common.protobuf.MsgBuilder.ProtoMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new common.protobuf.MsgBuilder.ProtoMsg();
    }

    public static common.protobuf.MsgBuilder.ProtoMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProtoMsg>
        PARSER = new com.google.protobuf.AbstractParser<ProtoMsg>() {
      public ProtoMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoMsg> getParserForType() {
      return PARSER;
    }

    public common.protobuf.MsgBuilder.ProtoMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_protobuf_ProtoMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_protobuf_ProtoMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\017common.protobuf\"\213\002\n\010ProtoMs" +
      "g\022\n\n\002id\030\001 \002(\003\022\017\n\007from_id\030\002 \001(\005\022\017\n\007dest_i" +
      "d\030\003 \001(\005\022\021\n\tclient_id\030\004 \001(\003\022\021\n\tdialog_id\030" +
      "\005 \001(\t\022*\n\010msg_type\030\006 \002(\0162\030.common.protobu" +
      "f.MsgType\022\014\n\004body\030\007 \001(\t\022(\n\005state\030\010 \001(\0162\031" +
      ".common.protobuf.AckState\022\014\n\004time\030\t \001(\004\022" +
      "\013\n\003cmd\030\n \001(\t\022,\n\tchat_type\030\013 \002(\0162\031.common" +
      ".protobuf.ChatType**\n\010ChatType\022\010\n\004Text\020\001" +
      "\022\t\n\005Photo\020\002\022\t\n\005Audio\020\003*{\n\010AckState\022\016\n\nCl" +
      "ientSend\020\001\022\021\n\rServerReceive\020\002\022\016\n\nServerS",
      "end\020\003\022\021\n\rClientReceive\020\004\022\016\n\nClientRead\020\005" +
      "\022\016\n\nServerRead\020\006\022\t\n\005Error\020\007*[\n\007MsgType\022\010" +
      "\n\004Ping\020\001\022\010\n\004Pong\020\002\022\010\n\004Chat\020\003\022\013\n\007ChatAck\020" +
      "\004\022\007\n\003CMD\020\005\022\r\n\tBroadcast\020\006\022\r\n\tGroupChat\020\007" +
      "B\014B\nMsgBuilder"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_protobuf_ProtoMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_protobuf_ProtoMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_protobuf_ProtoMsg_descriptor,
        new java.lang.String[] { "Id", "FromId", "DestId", "ClientId", "DialogId", "MsgType", "Body", "State", "Time", "Cmd", "ChatType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
